### ISSUE TITLE
must extend class OutlookFormRegion

### ISSUE THREAD

**Issue by xgouchet** [wolfgangimig/joa#5]
Hi, I'm trying to use your library, following your tutorial I created the following class : 

    @CoClass(progId="MyAddin.Class", guid="{7e6f5d9a-743b-4198-876c-9c18472b254c}")
    @DeclAddin(friendlyName="Foo", description="", application=OfficeApplication.Outlook, loadBehavior=LoadBehavior.LoadOnStart)
    public class MyAddin extends OutlookAddin {
    }

But upon compilation, I get an error in the generated Module class : 

  "MyAddin mus extend class com.wilutions.joa.outlook.OutlookFormRegion". 

I'm uisng the library from release 0.4.0. 

Help me, Wolfgangimig. You're my only hope !

**Comment by wolfgangimig** [comment]
Hello xgouchet,
some days ago I encountered the same problem when trying to compile a JOA based Addin in IntelliJ. The problem was caused in the annotation processor joa-processor.jar. For some reason, a plausibility check failed. I removed the dispensable code, re-built the project and the problem was solved.
Please checkout the master branch and try again.
Regards,
Wolfgang

**Comment by xgouchet** [comment]
Thanks a lot, this works now !
